import os
import uuid
import shutil
import subprocess

from flask import Flask, render_template, request, redirect, url_for, session
from flask_cors import CORS

# ✅ IMPORTANT: this is your existing module that runs the 4 algorithms and produces CSV files
# It MUST generate:
#   Code/GeneratedData/wolf_fun_fitness.csv
#   Code/GeneratedData/bee_fun_fitness.csv
#   Code/GeneratedData/bat_fun_fitness.csv
#   Code/GeneratedData/fish_fun_fitness.csv
from Code import Michalewicz_Code


app = Flask(__name__)
CORS(app)
app.secret_key = os.environ.get("FLASK_SECRET_KEY", "dev-secret-change-me")


# -----------------------------
# Helpers
# -----------------------------
def find_rscript():
    # 1) If you set it manually in env
    rscript = os.environ.get("RSCRIPT_PATH", "").strip()
    if rscript and os.path.exists(rscript):
        return rscript

    # 2) Try PATH (Linux + Mac + Windows if installed properly)
    rscript = shutil.which("Rscript")
    if rscript and os.path.exists(rscript):
        return rscript

    # 3) Windows fallback (only useful locally)
    guess = r"C:\Program Files\R\R-4.5.2\bin\x64\Rscript.exe"
    if os.path.exists(guess):
        return guess

    raise FileNotFoundError(
        "Rscript not found. On Render, install R (Docker) or set RSCRIPT_PATH."
    )


def run_r(script_path, run_dir, timeout=600, extra_args=None):
    rscript = find_rscript()

    cmd = [rscript, script_path, run_dir]
    if extra_args:
        cmd.extend([str(x) for x in extra_args])

    try:
        result = subprocess.run(
            cmd,
            cwd=run_dir,
            capture_output=True,
            text=True,
            timeout=timeout
        )
    except subprocess.TimeoutExpired:
        raise RuntimeError(f"R script timed out after {timeout} seconds: {cmd}")

    if result.returncode != 0:
        raise RuntimeError(
            f"R script failed!\nCMD: {' '.join(cmd)}\n"
            f"STDOUT:\n{result.stdout}\n"
            f"STDERR:\n{result.stderr}"
        )


def ensure_run_outputs_in_run_dir(run_dir):
    """
    Copy your algorithm CSV outputs from Code/GeneratedData -> static/runs/<run_id>/
    """
    src_dir = os.path.join(app.root_path, "Code", "GeneratedData")
    if not os.path.isdir(src_dir):
        raise FileNotFoundError(f"Missing folder: {src_dir}")

    needed = [
        "wolf_fun_fitness.csv",
        "bee_fun_fitness.csv",
        "bat_fun_fitness.csv",
        "fish_fun_fitness.csv",
    ]

    for f in needed:
        src = os.path.join(src_dir, f)
        if not os.path.exists(src):
            raise FileNotFoundError(f"Missing file generated by algorithms: {src}")
        shutil.copy2(src, os.path.join(run_dir, f))


# =========================================================
# Your ORIGINAL routes (kept)
# =========================================================
@app.route("/")
def home():
    return render_template("div.html")


@app.route("/vis")
def vis():
    return render_template("vis.html")


@app.route("/learn")
def learn():
    return render_template("learn.html")


@app.route("/summary_act")
def summary_act():
    return render_template("summary_act.html")


@app.route("/bat_act")
def bat_act():
    return render_template("bat_act.html")


@app.route("/fish_act")
def fish_act():
    return render_template("fish_act.html")


@app.route("/wolf_act")
def wolf_act():
    return render_template("wolf_act.html")


@app.route("/bee_act")
def bee_act():
    return render_template("bee_act.html")


@app.route("/wolf_ack")
def wolf_ack():
    return render_template("Wolf/Wolf Ackley/wolf_ack.html")


@app.route("/fish_ack")
def fish_ack():
    return render_template("Fish/Fish Ackley/fish_ack.html")


@app.route("/bat_ack")
def bat_ack():
    return render_template("Bat/Bat Ackley/bat_ack.html")


@app.route("/bee_ack")
def bee_ack():
    return render_template("Bee/Bee Ackley/bee_ack.html")


@app.route("/best_sum_ackley")
def best_sum_ackley():
    return render_template("best_sum_ackley.html")


@app.route("/avg_sum_ackley")
def avg_sum_ackley():
    return render_template("avg_sum_ackley.html")


@app.route("/avg_sum_mic")
def avg_sum_mic():
    return render_template("avg_sum_mic.html")


@app.route("/best_sum_mic")
def best_sum_mic():
    return render_template("best_sum_mic.html")


@app.route("/wolf_mic")
def wolf_mic():
    return render_template("Wolf/Wolf Michalwicz/wolf_mic.html")


@app.route("/bat_mic")
def bat_mic():
    return render_template("Bat/Bat Michalewicz/bat_mic.html")


@app.route("/fish_mic")
def fish_mic():
    return render_template("Fish/Fish Michalwicz/fish_mic.html")


@app.route("/bee_mic")
def bee_mic():
    return render_template("Bee/Bee Michalewicz/bee_mic.html")


@app.route("/wolf_ackley")
def wolf_ackley():
    return render_template("Wolf/Wolf Ackley/wolf_ackley.html")


@app.route("/fish_ackley")
def fish_ackley():
    return render_template("Fish/Fish Ackley/fish_ackley.html")


@app.route("/bat_ackley")
def bat_ackley():
    return render_template("Bat/Bat Ackley/bat_ackley.html")


@app.route("/bee_ackley")
def bee_ackley():
    return render_template("Bee/Bee Ackley/bee_ackley.html")


@app.route("/wolf_michalewicz")
def wolf_michalewicz():
    return render_template("Wolf/Wolf Michalwicz/wolf_michalewicz.html")


@app.route("/fish_michalewicz")
def fish_michalewicz():
    return render_template("Fish/Fish Michalwicz/fish_michalewicz.html")


@app.route("/bat_michalewicz")
def bat_michalewicz():
    return render_template("Bat/Bat Michalewicz/bat_michalewicz.html")


@app.route("/bee_michalewicz")
def bee_michalewicz():
    return render_template("Bee/Bee Michalewicz/bee_michalewicz.html")


@app.route("/wolf")
def wolf():
    return render_template("Wolf/index.html")


@app.route("/bee")
def bee():
    return render_template("Bee/index.html")


@app.route("/bat")
def bat():
    return render_template("Bat/index.html")


@app.route("/fish")
def fish():
    return render_template("Fish/index.html")


@app.route("/fun_fit")
def fun_fit():
    return render_template("fun_fit.html")


@app.route("/mic_fit")
def mic_fit():
    return render_template("mic_fit.html")


@app.route("/ackley_fit")
def ackley_fit():
    return render_template("ackley_fit.html")


# =========================================================
# CUSTOM FLOW (NO DOUBLE SIDEBAR)
# =========================================================
@app.route("/custom_fit")
def custom_fit():
    # ✅ IMPORTANT: clear old error so it doesn't show when opening the page
    custom_error = session.pop("custom_error", None)
    return render_template("custom_fit.html", custom_error=custom_error)


@app.route("/custom_ui")
def custom_ui():
    # ✅ MUST be simple page (NO sidebar), because it sits in iframe
    return render_template("your_custom_builder.html")


@app.route("/custom_results")
def custom_results():
    run_id = session.get("run_id")
    if not run_id:
        return redirect(url_for("custom_fit"))
    return render_template(
        "custom_results.html",
        run_id=run_id,
        expr=session.get("custom_expr", ""),
        it=session.get("custom_it", ""),
        gen=session.get("custom_gen", ""),
        lb=session.get("custom_lb", ""),
        ub=session.get("custom_ub", ""),
    )


@app.route("/gif/<algo>/<metric>")
def gif_page(algo, metric):
    run_id = session.get("run_id")
    if not run_id:
        return redirect(url_for("custom_fit"))

    algo = algo.lower()
    metric = metric.lower()

    gif_map = {
        ("wolf", "best"): "Wolf_Fun_Best.gif",
        ("wolf", "average"): "Wolf_Fun_Average.gif",
        ("bee", "best"): "Bee_Fun_Best.gif",
        ("bee", "average"): "Bee_Fun_Average.gif",
        ("bat", "best"): "Bat_Fun_Best.gif",
        ("bat", "average"): "Bat_Fun_Average.gif",
        ("fish", "best"): "Fish_Fun_Best.gif",
        ("fish", "average"): "Fish_Fun_Average.gif",
    }

    if (algo, metric) not in gif_map:
        return redirect(url_for("custom_results"))

    run_dir = os.path.join(app.root_path, "static", "runs", run_id)
    filename = gif_map[(algo, metric)]
    gif_path = os.path.join(run_dir, filename)

    try:
        # define script paths
        pre = os.path.join(app.root_path, "Code", "Preprocessing_run.R")
        one = os.path.join(app.root_path, "Code", "SummaryVis_one.R")

        # ✅ 1) Run preprocessing ONLY if needed
        marker = os.path.join(run_dir, "datawolf.csv")
        if not os.path.exists(marker):
            run_r(pre, run_dir, timeout=600)

        # ✅ 2) Generate GIF ONLY if it doesn't exist
        if not os.path.exists(gif_path):
            run_r(one, run_dir, timeout=600, extra_args=[algo, metric])

    except Exception as e:
        session["custom_error"] = str(e)
        return redirect(url_for("custom_fit"))

    return render_template(
        "gif_view.html",
        run_id=run_id,
        expr=session.get("custom_expr", ""),
        algo=algo,
        metric=metric,
        gif_file=filename
    )


@app.route("/pick_gif")
def pick_gif():
    algo = request.args.get("algo", "wolf").lower()
    metric = request.args.get("metric", "best").lower()
    return redirect(url_for("gif_page", algo=algo, metric=metric))


# =========================================================
# RUN CUSTOM (REAL ALGORITHMS + R GIFS)
# =========================================================
@app.route("/run_custom", methods=["POST"])
def run_custom():
    # Form fields (from iframe)
    fun_expr = request.form.get("expr", "").strip()
    lb = request.form.get("lb", "-5").strip()
    ub = request.form.get("ub", "5").strip()
    it = request.form.get("it", "40").strip()     # individuals/population
    gen = request.form.get("gen", "60").strip()   # iterations/generations

    # Validate numeric
    try:
        lb_f = float(lb)
        ub_f = float(ub)
        it_i = int(it)
        gen_i = int(gen)
    except Exception:
        session["custom_error"] = "Invalid numeric inputs."
        return redirect(url_for("custom_fit"))

    if not fun_expr:
        session["custom_error"] = "Please enter a function."
        return redirect(url_for("custom_fit"))

    if lb_f >= ub_f:
        session["custom_error"] = "Lower bound must be strictly smaller than upper bound."
        return redirect(url_for("custom_fit"))

    # Save inputs
    session["custom_expr"] = fun_expr
    session["custom_lb"] = lb_f
    session["custom_ub"] = ub_f
    session["custom_it"] = it_i
    session["custom_gen"] = gen_i

    # New run folder
    run_id = uuid.uuid4().hex[:10]
    session["run_id"] = run_id

    run_dir = os.path.join(app.root_path, "static", "runs", run_id)
    os.makedirs(run_dir, exist_ok=True)

    # 1) Run YOUR real algorithms (Wolf/Bee/Bat/Fish)
    try:
        status = Michalewicz_Code.check(it_i, gen_i, lb_f, ub_f, fun_expr)
        if str(status).lower() == "error":
            session["custom_error"] = "Error: function invalid or bounds incorrect."
            return redirect(url_for("custom_fit"))
    except Exception as e:
        session["custom_error"] = f"Algorithm run failed: {e}"
        return redirect(url_for("custom_fit"))

    # 2) Copy those outputs into this run folder
    try:
        ensure_run_outputs_in_run_dir(run_dir)
    except Exception as e:
        session["custom_error"] = f"Missing outputs: {e}"
        return redirect(url_for("custom_fit"))

    # 3) Run R preprocessing + GIF generation IN this run folder
    try:
        pre = os.path.join(app.root_path, "Code", "Preprocessing_run.R")
        vis = os.path.join(app.root_path, "Code", "SummaryVis_run.R")

        if not os.path.exists(pre):
            raise FileNotFoundError(f"Missing: {pre}")
        if not os.path.exists(vis):
            raise FileNotFoundError(f"Missing: {vis}")

        # run_r(pre, run_dir, timeout=600)
        # run_r(vis, run_dir, timeout=600)
    except Exception as e:
        session["custom_error"] = str(e)
        return redirect(url_for("custom_fit"))

    return redirect(url_for("custom_results"))


if __name__ == "__main__":
    app.run(debug=True, port=5000)
